name: Continous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
    - name: npm install migrate and test
      run: |
        npm install
        npm run migrate up
        npm run test
      env:
        CI: true
        PGHOST_TEST: ${{ secrest.PGHOST_TEST }}
        PGUSER_TEST: ${{ secrest.PGUSER_TEST }}
        PGDATABASE_TEST: ${{ secrest.PGDATABASE_TEST }}
        PGPASSWORD_TEST: ${{ secrest.PGPASSWORD_TEST }}
        PGPORT_TEST: ${{ secrest.PGPORT_TEST }}
        PGHOST: ${{ secrest.PGHOST_TEST }}
        PGUSER: ${{ secrest.PGUSER_TEST }}
        PGDATABASE: ${{ secrest.PGDATABASE_TEST }}
        PGPASSWORD: ${{ secrest.PGPASSWORD_TEST }}
        PGPORT: ${{ secrest.PGPORT_TEST }}
        ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
        REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
        ACCESS_TOKEN_AGE: ${{ secrets.ACCESS_TOKEN_AGE }}